<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="TicketService"
                  targetNamespace="http://example.com/ticket"
                  xmlns:tns="http://example.com/ticket"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:ker="http://kereta.com/">

  <wsdl:types>
    <xsd:schema targetNamespace="http://kereta.com/">
      <xsd:import namespace="http://kereta.com/" schemaLocation="ticket.xsd"/>
    </xsd:schema>
  </wsdl:types>

  <!-- Request and Response Messages -->
  <wsdl:message name="GetTicketsRequest"/>
  <wsdl:message name="GetTicketsResponse">
    <wsdl:part name="tickets" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="AddTicketRequest">
    <wsdl:part name="name" type="xsd:string"/>
    <wsdl:part name="train" type="xsd:string"/>
    <wsdl:part name="date" type="xsd:string"/>
  </wsdl:message>
  <wsdl:message name="AddTicketResponse">
    <wsdl:part name="result" type="xsd:string"/>
  </wsdl:message>

  <!-- PortType -->
  <wsdl:portType name="TicketPortType">
    <wsdl:operation name="GetTickets">
      <wsdl:input message="tns:GetTicketsRequest"/>
      <wsdl:output message="tns:GetTicketsResponse"/>
    </wsdl:operation>
    <wsdl:operation name="AddTicket">
      <wsdl:input message="tns:AddTicketRequest"/>
      <wsdl:output message="tns:AddTicketResponse"/>
    </wsdl:operation>
  </wsdl:portType>

  <!-- Binding -->
  <wsdl:binding name="TicketBinding" type="tns:TicketPortType">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="GetTickets">
      <soap:operation soapAction="getTickets"/>
      <wsdl:input>
        <soap:body use="encoded" namespace="urn:ticket" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="encoded" namespace="urn:ticket" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AddTicket">
      <soap:operation soapAction="addTicket"/>
      <wsdl:input>
        <soap:body use="encoded" namespace="urn:ticket" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="encoded" namespace="urn:ticket" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

  <!-- Service -->
  <wsdl:service name="TicketService">
    <wsdl:port name="TicketPort" binding="tns:TicketBinding">
      <soap:address location="http://localhost:3000/wsdl"/>
    </wsdl:port>
  </wsdl:service>

</wsdl:definitions>
