<?xml version="1.0" encoding="UTF-8"?>
<definitions name="TicketService"
             targetNamespace="http://example.com/ticket"
             xmlns:tns="http://example.com/ticket"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:ker="http://example.com/ticket"
             xmlns="http://schemas.xmlsoap.org/wsdl/">

<!-- <types>
    <xsd:schema targetNamespace="http://example.com/ticket">
      <xsd:element name="AddTicketRequest">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="ticket">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="name" type="xsd:string"/>
                  <xsd:element name="train" type="xsd:string"/>
                  <xsd:element name="date" type="xsd:date"/>
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>

      <xsd:element name="AddTicketResponse">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="result" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </types> -->

 <types>
    <xsd:schema targetNamespace="http://example.com/ticket"
                elementFormDefault="qualified"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://example.com/ticket" schemaLocation="http://localhost:3000/wsdl/ticket.xsd"/>
    </xsd:schema>
  </types>

  <message name="GetTicketsRequest"/>
  <message name="GetTicketsResponse">
    <part name="tickets" element="tns:tickets"/>
  </message>

  <message name="AddTicketRequest">
    <part name="ticket" element="tns:ticket"/>
  </message>
  <message name="AddTicketResponse">
    <part name="result" type="xsd:string"/>
  </message>

  <message name="UpdateTicketRequest">
    <part name="ticket" element="tns:ticket"/>
  </message>
  <message name="UpdateTicketResponse">
    <part name="result" type="xsd:string"/>
  </message>

  <message name="DeleteTicketRequest">
    <part name="id" type="xsd:string"/>
  </message>
  <message name="DeleteTicketResponse">
    <part name="result" type="xsd:string"/>
  </message>


  <portType name="TicketPortType">
    <operation name="GetTickets">
      <input message="tns:GetTicketsRequest"/>
      <output message="tns:GetTicketsResponse"/>
    </operation>
    <operation name="AddTicket">
      <input message="tns:AddTicketRequest"/>
      <output message="tns:AddTicketResponse"/>
    </operation>
    <operation name="UpdateTicket">
      <input message="tns:UpdateTicketRequest"/>
      <output message="tns:UpdateTicketResponse"/>
    </operation>

    <operation name="DeleteTicket">
      <input message="tns:DeleteTicketRequest"/>
      <output message="tns:DeleteTicketResponse"/>
    </operation>
  </portType>

  <binding name="TicketBinding" type="tns:TicketPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="GetTickets">
      <soap:operation soapAction="http://example.com/ticket/GetTicket"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
    <operation name="AddTicket">
      <soap:operation soapAction="http://example.com/ticket/AddTicket"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
    <operation name="UpdateTicket">
      <soap:operation soapAction="http://example.com/ticket/UpdateTicket"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>

    <operation name="DeleteTicket">
      <soap:operation soapAction="http://example.com/ticket/DeleteTicket"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>

  <service name="TicketService">
    <port name="TicketPortType" binding="tns:TicketBinding">
      <soap:address location="http://localhost:3000/wsdl"/>
    </port>
  </service>

</definitions>
