<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://example.com/ticket"
    xmlns="http://example.com/ticket"
    elementFormDefault="qualified">

  <xsd:element name="AddTicketRequest">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="ticket">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="name" type="xsd:string"/>
              <xsd:element name="train" type="xsd:string"/>
              <xsd:element name="date" type="xsd:date"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="AddTicketResponse">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="result" type="xsd:string"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="tickets">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="ticket" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="name" type="xsd:string"/>
              <xsd:element name="train" type="xsd:string"/>
              <xsd:element name="date" type="xsd:date"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>
